import type { NextPage } from "next";
import Head from "next/head";
import { Box } from "@chakra-ui/react";
import DataGridSample from "../src/components/organisms/DataGridSample";

const Home: NextPage = () => {
  return (
    <Box padding={8} as="main">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <DataGridSample />
    </Box>
  );
};

export default Home;
