import type { NextPage } from "next";
import Head from "next/head";

import { Box } from "@chakra-ui/react";
import DataGridSample from "../src/components/organisms/DataGridSample";
import { generateRows } from "../src/lib/sampleData";

const records = generateRows(1000); // 本来はデータをサーバ等からfetchする想定

const Home: NextPage = () => {
  return (
    <Box padding={8} as="main">
      <Head>
        <title>DataGrid Sample</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <DataGridSample records={records} />
    </Box>
  );
};

export default Home;
