import type { NextPage } from "next";
import Head from "next/head";
import { Box, Text } from "@chakra-ui/react";

const Home: NextPage = () => {
  return (
    <Box as="main">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box maxW="sm">
        <Text>Hello, Chakra UI!</Text>
      </Box>
    </Box>
  );
};

export default Home;
